apiVersion: v1
data:
  koti.lan.server: |
    koti.lan:53 {
        log
        kubernetes koti.lan

        rewrite name dav.koti.lan koti-ingress-nginx-controller.ingress-nginx.svc.koti.lan
        rewrite name feed.koti.lan miniflux.default.svc.koti.lan
        rewrite name g.koti.lan grafana.monitoring.svc.koti.lan
        rewrite name files.garage.koti.lan garage.default.svc.koti.lan
        rewrite name pass.koti.lan koti-ingress-nginx-controller.ingress-nginx.svc.koti.lan
        rewrite name red.koti.lan koti-ingress-nginx-controller.ingress-nginx.svc.koti.lan
    }
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
