apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        arch: "amd64"
      containers:
        - name: registry
          image: registry
          volumeMounts:
            - name: repo
              mountPath: "/var/lib/registry"
            - name: auth
              mountPath: "/auth"
              readOnly: true
                # - name: certs
                #   mountPath: "/certs"
                #   readOnly: true
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
                # - name: REGISTRY_HTTP_TLS_CERTIFICATE
                #   value: "/certs/tls.crt"
                # - name: REGISTRY_HTTP_TLS_KEY
                #   value: "/certs/tls.key"
          ports:
            - name: http
              containerPort: 5000
      volumes:
        - name: repo
          persistentVolumeClaim:
            claimName: registry-repo
              # - name: certs
              #   secret:
              #     secretName: registry-certs
        - name: auth
          secret:
            secretName: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  # type: NodePort
  selector:
    app: registry
  ports:
    - name: http
      port: 5000
      targetPort: 5000
        #   nodePort: 30019
