apiVersion: apps/v1
kind: Deployment
metadata:
  name: readit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readit
  template:
    metadata:
      labels:
        app: readit
    spec:
      containers:
        - name: readit
          image: sini:5000/readit:latest
          ports:
            - containerPort: 3000
          env:
            - name: READIT_PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: readit
spec:
  selector:
    app: readit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readit
spec:
  ingressClassName: nginx
  rules:
    - host: red.koti.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readit
                port:
                  number: 80
