apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarr
  labels:
    app: yarr
spec:
  selector:
    matchLabels:
      app: yarr
  template:
    metadata:
      labels:
        app: yarr
    spec:
      containers:
        - name: yarr
          image: sini:5000/yarr:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7070
          args:
            - -addr 
            - 0.0.0.0:7070
          volumeMounts:
            - name: db
              mountPath: /data
      volumes:
        - name: db 
          persistentVolumeClaim:
            claimName: yarr-db

---
apiVersion: v1
kind: Service
metadata:
  name: yarr
spec:
  selector:
    app: yarr
  ports:
    - name: http
      port: 80
      targetPort: 7070
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yarr-db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
