apiVersion: apps/v1
kind: Deployment
metadata:
  name: honk
  labels:
    app: honk
spec:
  selector:
    matchLabels:
      app: honk
  template:
    metadata:
      labels:
        app: honk
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: honk
          image: sini:5000/honk:latest
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          args:
            - -datadir
            - /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: honk-data
        - name: certs
          hostPath:
            path: /etc/ssl/certs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: honk-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: honk
spec:
  selector:
    app: honk
  ports:
    - name: honk-http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h.icyphox.sh
  namespace: default
spec:
  ingressClassName: caddy
  rules:
  - host: h.icyphox.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: honk
            port:
              number: 8080
