apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: audiobookshelf
  namespace: default
spec:
  chart: oci://tccr.io/truecharts/audiobookshelf
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        size: 2Gi
        mountPath: /config
      audiobooks:
        enabled: true
        existingClaim: transmission-data
        mountPath: /audiobooks
      metadata:
        size: 1Gi
        enabled: true
        mountPath: /metadata
