apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn
  valuesContent: |-
    defaultSettings:
      defaultReplicaCount: 2
