apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres
  namespace: default
spec:
  chart: oci://registry-1.docker.io/bitnamicharts/postgresql
  targetNamespace: default
  valuesContent: |-
    fullnameOverride: postgres
    image:
      tag: 16
