apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  targetNamespace: tailscale
