apiVersion: apps/v1
kind: Deployment
metadata:
  name: legit
  labels:
    app: legit
spec:
  selector:
    matchLabels:
      app: legit
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: legit
    spec:
      containers:
        - name: legit
          image: sini:5000/legit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
          args:
            - -config
            - /config.yaml
          volumeMounts:
            - name: repos
              mountPath: /var/www/git
              readOnly: true
      volumes:
        - name: repos
          hostPath:
            path: /home/git
---
apiVersion: v1
kind: Service
metadata:
  name: legit
spec:
  selector:
    app: legit
  ports:
    - name: legit-http
      port: 5555 
      targetPort: 5555
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git.icyphox.sh
  namespace: default
spec:
  ingressClassName: caddy
  rules:
  - host: git.icyphox.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: legit
            port:
              number: 5555

