apiVersion: v1
data:
  lms.conf: |
    # LMS Sample configuration file

    # Path to the working directory
    # Must have write privileges in order to create and modify this directory
    working-dir = "/var/lms/";

    # ffmpeg location
    ffmpeg-file = "/usr/bin/ffmpeg";

    # Log files, empty means stdout
    log-file = "";
    access-log-file = "";
    # Logger configuration, see log-config in https://webtoolkit.eu/wt/doc/reference/html/overview.html#config_general
    log-config = "* -debug -info:WebRequest";

    # Listen port/addr of the web server
    listen-port = 5082;
    listen-addr = "0.0.0.0";
    behind-reverse-proxy = true;

    # If enabled, these files have to exist and have correct permissions
    tls-enable = false;
    tls-cert = "/var/lms/cert.pem";
    tls-key = "/var/lms/privkey.pem";
    tls-dh = "/var/lms/dh2048.pem";

    # Path to the resources used by the web interface.
    wt-resources = "/usr/share/Wt/resources";
    docroot = "/etc/lms/docroot/;/resources,/css,/images,/js,/favicon.ico";
    approot = "/usr/share/lms/approot";
    # Location for deployment (See README if you want to deploy on a non root path)
    deploy-path = "/";

    # Number of threads to be used to dispatch http requests (0 means auto detect)
    http-server-thread-count = 0;

    # ListenBrainz root API
    listenbrainz-api-url = "https://api.listenbrainz.org/1/";

    # Acousticbrainz root API
    acousticbrainz-api-url = "https://acousticbrainz.org/api/v1/";

    # Authentication
    # Available backends: "internal", "PAM", "http-headers"
    authentication-backend = "internal";
    http-headers-login-field = "X-Forwarded-User";

    # Max entries in the login throttler (1 entry per IP address. For IPv6, the whole /64 block is used)
    login-throttler-max-entries = 10000;

    # API
    api-subsonic = true;

    # Turn on this option to allow the demo account creation/use
    demo = false;

    # Max external cover file size in MBytes
    cover-max-file-size = 10;

    # Max cover cache size in MBytes
    cover-max-cache-size = 30;

    # JPEG quality for covers (range is 1-100)
    cover-jpeg-quality = 100;
kind: ConfigMap
metadata:
  name: lms-config
