apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-persist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-ui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
