apiVersion: apps/v1
kind: Deployment
metadata:
  name: znc
  labels:
    app: znc
spec:
  selector:
    matchLabels:
      app: znc
  template:
    metadata:
      labels:
        app: znc
    spec:
      nodeSelector:
        arch: "amd64"
      imagePullSecrets:
        - name: registry-creds
      containers:
        - name: znc
          image: znc:slim
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/znc-data"
              readOnly: false
          ports:
            - name: irc
              containerPort: 6666
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: znc-config-dir
---
apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  type: LoadBalancer
  selector:
    app: znc
  ports:
    - name: irc
      port: 6666
      targetPort: 6666
