apiVersion: v1
kind: Service
metadata:
  name: pixelfed
spec:
  # selector:
  #   app: pixelfed
  ports:
    - name: pixelfed-http
      port: 80
      targetPort: 3535
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pixelfed
subsets:
- addresses:
  - ip: 192.168.100.30
  ports:
  - port: 3535
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ani.place
  namespace: default
spec:
  ingressClassName: caddy
  rules:
  - host: ani.place
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pixelfed
            port:
              number: 80

