apiVersion: v1
kind: Service
metadata:
  name: pixelfed
spec:
  type: ExternalName
  externalName: sini
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ani.place
  namespace: default
spec:
  ingressClassName: caddy
  rules:
  - host: ani.place
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pixelfed
            port:
              number: 3535
