apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dav-koti-lan
  namespace: default
spec:
  secretName: dav-koti-lan
  isCA: false
  commonName: "dav.koti.lan"
  dnsNames:
  - "dav.koti.lan"
  issuerRef:
    name: koti-ca-issuer
