apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pass-koti-lan
  namespace: default
spec:
  secretName: pass-koti-lan
  isCA: false
  commonName: "pass.koti.lan"
  dnsNames:
  - "pass.koti.lan"
  issuerRef:
    name: koti-ca-issuer
